### ISSUE TITLE
Merge sort Line 20

### ISSUE THREAD

**Issue by kkartaltepe** [gegenpressing/Data-structures-and-algorithms#1]
[Line 20](https://github.com/gegenpressing/Data-structures-and-algorithms/blob/master/merge_sort.py#L20) You copy from `len(list) - len(list)/2` but you should copy from where left side ended. E.G. if left side was `len(list)/2+1` now you have a duplicate item in left and right side.

**Comment by gegenpressing** [comment]
But shouldn't that be right though since I set my condition that this happens if the list is odd? I ran it again and only found that to be true if it's even where there's a duplicate item in the left and right side, but works as I need it to be if it's odd.

**Comment by kkartaltepe** [comment]
Yes lines 16-19 are fine, but the problem is line 20 where you do the same thing regardless of if its odd or even.

Line 20 should copy from the where you have `len(unsortedlist) - len(unsortedlist)/2:len(unsortedlist)` the part that is wrong here is `len(unsortedlist)/2:len(unsortedlist)`. This is wrong because it doesnt change based on what you did in lines 16-19 (based on the oddness or evenness of length).

 What you should replace this with is something like `len(unsortedlist) - len(unsortedlistleftside)`. Now you are taking into account if it was odd or even and ENSURING that `len(unsortedlistleftside)+len(unsortedlistrightside) == len(unsortedlist)`

**Comment by gegenpressing** [comment]
Oh snap. On it.

**Comment by gegenpressing** [comment]
That should do it. Ran it with different list size to make sure the result is consistent. Hope this is good.
