### ISSUE TITLE
Merge sort variable names

### ISSUE THREAD

**Issue by kkartaltepe** [gegenpressing/Data-structures-and-algorithms#2]
You call the lists `unsortedleftside` and `unsortedrightside` but after the call to `merge_sort(unsortedleftside)` and `merge_sort(unsortedrightside)` it IS sorted and you are simply merging sorted lists. You mention that they are unsorted again in some comments discussing the split lists but they are already sorted and you only have to merge them. THAT is the magic.

**Comment by kkartaltepe** [comment]
Oh after the call you make the variables `unsortedsublistrightside` but it should just be `sortedrightside` because thats what the recursive call does. It sorts the right side.

**Comment by gegenpressing** [comment]
Duly noted. Fixed.
