### ISSUE TITLE
do NOT use += when assigning integer values.

### ISSUE THREAD

**Issue by kkartaltepe** [gegenpressing/Data-structures-and-algorithms#3]
You use `+=` to assign the value to the `0` initialized list `sortedlist`. You should not do this because it obscures the meaning. Someone only reading the assignment section will be confused as to whether this is actually a merge sort or some sort of strange adding function. And if anyone were to change the initialization to start at anything but 0 (suppose they wanted it to start at -1) then your merge sort will change all the values by -1 for each level it recurses. If you want to assign a value use `=` only use `+=` if you want to increment a value.

`+=` is also concatenation in python so it could lead to even more weird funky shit instead of actually assigning the value to the array. If someone initialized the array with strings it would append to the initialized value.

**Comment by gegenpressing** [comment]
Duly noted. Fixed.
